# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-04 16:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('widthPixels', models.PositiveIntegerField()),
                ('heightPixels', models.PositiveIntegerField()),
            ],
        ),
    ]
