# Generated by Django 2.2.8 on 2019-12-11 20:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geophoto_api', '0004_auto_20191207_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codi', models.CharField(max_length=25)),
                ('area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25831)),
            ],
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
